import Button from '../Button/Button'
import classes from './Form.module.css'
import { useState } from 'react'
import { useAppDispatch } from '../../store/hooks/hooks'
import {addPost} from '../../store/reducers/postsSlice'


function Form() {

  
  const [id,setId]=useState(+Date.now())
  const [title,setTitle]=useState('')
  const [body,setBody]=useState('')
  const [userId]=useState(123)

  const dispatch = useAppDispatch();

  const addTask = () => {
    if(title.trim() === ''|| body.trim() === ''){
      alert('Fields must be filled');
    }
    else{
      dispatch(addPost({id,title,body,userId}));
      setTitle("");
      setBody("");
      setId(+Date.now())

    }
  };

const handleSubmit = (e: React.FormEvent) => {
  e.preventDefault();
}

  return (
    <form className={classes.form}  onSubmit={handleSubmit}>
      <h2 className={classes.form__title}>New post</h2>

      <label htmlFor=""> id (autogenerated)</label>
      <input className={classes.form__input} 
        type="text" 
        value={id} 
        disabled 
      />

        <label htmlFor="title">Title</label>
        <input id='title' className={classes.form__input} 
        type="text" 
        value={title} 
        onChange={(e)=>setTitle(e.target.value)}/>
        
        <label htmlFor="body">Post text</label>
        <input id='body' className={classes.form__input} 
        type="text" 
        value={body} 
        onChange={(e)=>setBody(e.target.value)}/>
        <label htmlFor="body">Your Id</label>
        <input id='body' className={classes.form__input} 
        type="text" 
        value={userId} 
        disabled/>

      <Button title="Add post" onClick={addTask} />
    </form>
  )
}

export default Form